// ignore_for_file: use_key_in_widget_constructors

import 'package:flutter/material.dart';
import 'package:intro_slider/intro_slider.dart';
import 'package:intro_slider/slide_object.dart';
import 'package:trans4/constants/constants.dart';
import 'package:trans4/ui/mainscreen.dart';

class Intro extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return IntroState();
  }
}

class IntroState extends State<Intro> {
  List<Slide> listSlides = [];

  @override
  Widget build(BuildContext context) {
    return IntroSlider(
      slides: listSlides,
      onDonePress: onPressedDone,
      onSkipPress: onPressedDone,
    );
  }

  @override
  void initState() {
    super.initState();
    listSlides.add(Slide(
      title: 'Welcome To Trans4',
      description: "IN CONFIDENTIALITY WE BELIEVE",
      pathImage: "assets/images/logo.png",
      backgroundColor: Colors.purple[700],
    ));
    listSlides.add(Slide(
      title: "Encrypt What You Want",
      description:
          "You can use your own key for encrypting message or can use autogenerated key",
      pathImage: "assets/images/encode.png",
      backgroundColor: Colors.deepOrange[600],
    ));
    listSlides.add(Slide(
      title: "Decrypt With Ease",
      description:
          "Just Upload your Encrypted Media with Key and get the Secret Message",
      pathImage: "assets/images/decode.png",
      backgroundColor: Colors.amber[600],
    ));
  }

  onPressedDone() {
    Navigator.of(context).pushReplacementNamed(SIGN_IN);
  }
}
